---
- hosts: all
  become: yes
  tasks:

  - name: Install needed repositories (apt)
    vars:
      ubuntu_codename: "{{ lookup('pipe', 'lsb_release -cs') }}"
    block:
      - name: Add System76 Pop PPA
        apt_repository:
          repo: ppa:system76/pop
          state: present
      - name: Add Multiverse Repository
        apt_repository:
          repo: "deb http://us.archive.ubuntu.com/ubuntu/ {{ ubuntu_codename }} multiverse"
          state: present
      - name: Add Graphics Driver PPA
        apt_repository:
          repo: ppa:graphics-drivers/ppa
          state: present
      - name: Add Lutris Repository
        apt_repository:
          repo: ppa:lutris-team/lutris
          state: present
      - name: Add Wine HQ Apt Key
        apt_key:
          url: https://dl.winehq.org/wine-builds/winehq.key
          state: present
      - name: Add Wine HQ Repository
        apt_repository:
          repo: "deb https://dl.winehq.org/wine-builds/ubuntu/ {{ ubuntu_codename }} main"
          state: present
      - name: Add Docker CE Apt Key
        apt_key:
          url: https://download.docker.com/linux/ubuntu/gpg
          state: present
      - name: Add Docker CE Repo
        apt_repository:
          repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ubuntu_codename }} stable"
          state: present
      - name: Add Seafile PPA
        apt_repository:
          repo: ppa:seafile/seafile-client
          state: present
    when: ansible_distribution == 'Ubuntu'

  - name: Install needed repositories (yum)
    vars:
      fedora_version: "{{ lookup('pipe', '. /etc/os-release && echo $VERSION_ID') }}"
    block:
      - name: Install RPMFusion Free
        yum:
          name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ fedora_version }}.noarch.rpm"
          state: present
      - name: Install RPMFusion Nonfree
        yum:
          name: "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ fedora_version }}.noarch.rpm"
          state: present
      - name: Install Google Chrome Repo
        yum_repository:
          name: google-chrome
          description: Google Chrome
          file: google-chrome
          baseurl: http://dl.google.com/linux/chrome/rpm/stable/x86_64
          gpgkey: https://dl.google.com/linux/linux_signing_key.pub
          gpgcheck: yes
          enabled: yes
      - name: Install Docker CE Repo
        yum_repository:
          name: docker-ce
          description: Docker CE Stable
          file: docker-ce
          baseurl: "https://download.docker.com/linux/fedora/{{ fedora_version }}/x86_64/stable"
          gpgkey: https://download.docker.com/linux/fedora/gpg
          gpgcheck: yes
          enabled: yes
      - name: Add Wine HQ Repo
        yum_repository:
          name: WineHQ
          description: WineHQ packages
          file: winehq
          baseurl: "https://dl.winehq.org/wine-builds/fedora/{{ fedora_version }}"
          gpgkey: https://dl.winehq.org/wine-builds/winehq.key
          gpgcheck: yes
          enabled: yes
    when: ansible_distribution == 'Fedora'

  - name: Enable 32-bit Architecture
    command: dpkg --add-architecture i386 
    when: ansible_distribution == 'Ubuntu'
  
  - name: Install needed packages (apt)
    block:
      - name: Update apt cache
        apt:
          update_cache: yes
      - name: Install packages
        apt:
          name:
            - containerd.io
            - docker-ce
            - docker-ce-cli
            - ffmpeg
            - git
            - gnome-tweak-tool
            - libasound2-plugins:i386 
            - libdbus-1-3:i386
            - libfreetype6:i386 
            - libgnutls30:i386 
            - libgpg-error0:i386
            - libldap-2.4-2:i386 
            - libsdl2-2.0-0:i386 
            - libsqlite3-0:i386
            - libxml2:i386 
            - lutris
            - pop-icon-theme
            - pop-gtk-theme
            - pop-gnome-shell-theme
            - python3-pip
            - python3-setuptools
            - p7zip-full
            - p7zip-rar
            - seafile-gui
            - steam-installer
            - ubuntu-restricted-extras
            - vim
            - vlc
            - winehq-stable
            - xz-utils
          state: present
      - name: Install Google Chrome
        apt:
          deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          state: present
      - name: Install Discord
        apt:
          deb: https://dl.discordapp.net/apps/linux/0.0.9/discord-0.0.9.deb
          state: present
    when: ansible_distribution == 'Ubuntu'

  - name: Install needed packages (yum)
    block:
      - name: Install packages
        yum:
          name:
            - containerd.io
            - Discord
            - docker-ce
            - docker-ce-cli
            - ffmpeg
            - git
            - gnome-tweak-tool
            - gnutls
            - gnutls-devel
            - google-chrome-stable
            - libgpg-error
            - lutris
            - openldap
            - openldap-devel
            - python3-pip
            - python3-setuptools
            - p7zip
            - seafile-client
            - snapd
            - sqlite2.i686
            - sqlite2.x86_64
            - steam
            - unzip
            - vlc
            - wine-stable
          state: present
      - name: Enable classic snap support
        file:
          src: /var/lib/snapd/snap
          dest: /snap
          state: link
    when: ansible_distribution == 'Fedora'

  - name: Remove unneeded software (apt)
    apt:
      name:
        - apport-gtk
      state: absent
    when: ansible_distribution == 'Ubuntu'

  - name: Install needed software (snap)
    block:
      - snap:
          name: 
          - pycharm-professional
          - code
          classic: yes
          state: present
      - snap:
          name:
          - spotify
          - telegram-desktop
          state: present
  
  - name: Install needed software (pip)
    pip:
      executable: pip3
      name:
        - ffmpeg
        - youtube-dl
      state: present

  - name: Do Docker Setup
    block:
      - name: Add primary user to docker group
        user:
          name: "{{ primary_user }}"
          append: yes
          groups: docker
      - name: Start and Enable Docker
        service:
          name: docker
          enabled: yes
          state: started

  - name: Enable Minimize on Click for the Ubuntu Dock
    command: gsettings set org.gnome.shell.extensions.dash-to-dock click-action 'minimize'
    when: ansible_distribution == 'Ubuntu'
